In [45]:
import geopandas as gpd
import pandas as pd
import numpy
import fiona

In [46]:
pplants = gpd.read_file(r'.\data\PowerPlants_US_EIA\PowerPlants_US_202001.shp')

In [47]:
pplants['combine'] = pplants[['Total_MW','Coal_MW','NG_MW','Crude_MW','Bio_MW','Hydro_MW','HydroPS_MW','Nuclear_MW','Solar_MW','Wind_MW','Geo_MW','Bat_MW','Other_MW']].values.tolist()

In [48]:
pplants.head(3)

,Plant_Code,Plant_Name,Utility_Na,Utility_ID,sector_nam,City,County,StateName,Zip,Street_Add,...,Bat_MW,Other_MW,source_des,tech_desc,Source,Period,Latitude,Longitude,geometry,combine
0,2,Bankhead Dam,Alabama Power Co,195,Electric Utility,Northport,Tuscaloosa,Alabama,35476,19001 Lock 17 Road,...,None,None,Hydroelectric = 53 MW,Conventional Hydroelectric,"EIA-860, EIA-860M and EIA-923",202001,33.458665,-87.356823,POINT (-87.35682 33.45867),"[53.0, 0.0, 0.0, 0.0, None, 53.0, 0.0, 0.0, 0...."
1,3,Barry,Alabama Power Co,195,Electric Utility,Bucks,Mobile,Alabama,36512,North Highway 43,...,None,None,"Coal = 1118.5 MW, Natural Gas = 1268.4 MW",Conventional Steam Coal; Natural Gas Fired Com...,"EIA-860, EIA-860M and EIA-923",202001,31.006900,-88.010300,POINT (-88.01030 31.00690),"[2386.9, 1118.5, 1268.4, 0.0, None, 0.0, 0.0, ..."
2,4,Walter Bouldin Dam,Alabama Power Co,195,Electric Utility,Wetumpka,Elmore,Alabama,36092,750 Bouldin Dam Road,...,None,None,Hydroelectric = 224.1 MW,Conventional Hydroelectric,"EIA-860, EIA-860M and EIA-923",202001,32.583889,-86.283056,POINT (-86.28306 32.58389),"[224.1, 0.0, 0.0, 0.0, None, 224.1, 0.0, 0.0, ..."

In [49]:
pd.DataFrame([dict([kv.split(' = ') for kv in record.split(', ')]) for record in pplants[['source_des']]])

ValueError: dictionary update sequence element #0 has length 1; 2 is required

In [50]:
pplants['test'] = pplants['source_des'].str.split(", ", n = -1, expand = False)

In [62]:
res = dict(item.split(" = ") for item in (pplants['source_des'].str.split(","))

SyntaxError: unexpected EOF while parsing (<ipython-input-62-af70343984a2>, line 1)

In [52]:
pplants['fuel'] = pplants.source_des.str.split(',',expand=False)

In [44]:
pplants.head(3)

,Plant_Code,Plant_Name,Utility_Na,Utility_ID,sector_nam,City,County,StateName,Zip,Street_Add,...,Other_MW,source_des,tech_desc,Source,Period,Latitude,Longitude,geometry,combine,fuel
0,2,Bankhead Dam,Alabama Power Co,195,Electric Utility,Northport,Tuscaloosa,Alabama,35476,19001 Lock 17 Road,...,None,Hydroelectric = 53 MW,Conventional Hydroelectric,"EIA-860, EIA-860M and EIA-923",202001,33.458665,-87.356823,POINT (-87.35682 33.45867),"[53.0, 0.0, 0.0, 0.0, None, 53.0, 0.0, 0.0, 0....",[Hydroelectric = 53 MW]
1,3,Barry,Alabama Power Co,195,Electric Utility,Bucks,Mobile,Alabama,36512,North Highway 43,...,None,"Coal = 1118.5 MW, Natural Gas = 1268.4 MW",Conventional Steam Coal; Natural Gas Fired Com...,"EIA-860, EIA-860M and EIA-923",202001,31.006900,-88.010300,POINT (-88.01030 31.00690),"[2386.9, 1118.5, 1268.4, 0.0, None, 0.0, 0.0, ...","[Coal = 1118.5 MW, Natural Gas = 1268.4 MW]"
2,4,Walter Bouldin Dam,Alabama Power Co,195,Electric Utility,Wetumpka,Elmore,Alabama,36092,750 Bouldin Dam Road,...,None,Hydroelectric = 224.1 MW,Conventional Hydroelectric,"EIA-860, EIA-860M and EIA-923",202001,32.583889,-86.283056,POINT (-86.28306 32.58389),"[224.1, 0.0, 0.0, 0.0, None, 224.1, 0.0, 0.0, ...",[Hydroelectric = 224.1 MW]

In [65]:
for item in pplants['fuel'] (dict(item.split("=") )

SyntaxError: unexpected EOF while parsing (<ipython-input-65-2f6aadbfeb78>, line 1)

In [63]:
(pplants['source_des'].str.split(","))

0                            [Hydroelectric = 53 MW]
1       [Coal = 1118.5 MW,  Natural Gas = 1268.4 MW]
2                         [Hydroelectric = 224.1 MW]
3                             [Natural Gas = 130 MW]
4                              [Natural Gas = 63 MW]
                            ...
9763                                [Solar = 1.4 MW]
9764                                [Solar = 1.9 MW]
9765                                  [Solar = 2 MW]
9766                                  [Solar = 2 MW]
9767                                  [Solar = 2 MW]
Name: source_des, Length: 9768, dtype: object